name: Convert Markdown to HTML and Deploy to GitHub Pages

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install markdown2

      - name: Create Python script
        run: |
          cat << 'EOF' > convert_md_to_html.py
          import sys
          import markdown2
          import os
          import re

          input_file = sys.argv[1]
          output_file = sys.argv[2]

          # Read Markdown content
          with open(input_file, 'r') as f:
              markdown_content = f.read()

          # Convert Markdown to HTML
          body_content = markdown2.markdown(markdown_content)

          # Read the HTML template
          with open('template.html', 'r') as f:
              template = f.read()

          # Extract title from the first heading in Markdown
          match = re.search(r'^#\s+(.*)', markdown_content, re.MULTILINE)
          if match:
              title = match.group(1)
          else:
              title = os.path.basename(input_file)

          # Replace placeholders in the template
          html_content = template.replace('{{ content }}', body_content)
          html_content = html_content.replace('{{ title }}', title)

          # Write the output HTML file
          with open(output_file, 'w') as f:
              f.write(html_content)
          EOF

      - name: Convert Markdown to HTML
        run: |
          for file in docs/*.md; do
            filename=$(basename -- "$file")
            name="${filename%.*}"
            python convert_md_to_html.py "$file" "docs/${name}.html"
          done

      - name: Disable Jekyll
        run: touch docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          destination_dir: .